### ISSUE TITLE
You should add a coercion from plain coderefs

### ISSUE THREAD

**Issue by tobyink** [ybrliiu/p5-Types-TypedCodeRef#4]
I've been thinking of making a typed coderef type myself at some point, so I'm glad someone else has done it for me!

Should be possible to do something like:

    has adder => ( is => 'ro', isa => TypedCodeRef[ [Int,Int] => Int ], coerce => 1 );
    ...;
    my $obj = $class->new( adder => sub { $_[0] + $_[1] } );

It should be possible to do with Type::Tiny's `coercion_generator`. If the documentation for that isn't very good, then feel free to ask my advice down there ↓

**Comment by ybrliiu** [comment]
Sure, I will try to implement coercions.

**Comment by ybrliiu** [comment]
I implemented coercions at https://github.com/ybrliiu/p5-Types-TypedCodeRef/pull/5.
thanks.

**Comment by tobyink** [comment]
Awesome :)
